### ISSUE TITLE
settings del repo

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#10]
@gbvitrano nei setting del repo, puoi creare una [milestone](https://help.github.com/articles/about-milestones/), e la chiami "rilascio 1.0"?

Così, markiamo le issue da chiudere prime del lancio e quelle anche successive.

Grazie

**Comment by gbvitrano** [comment]
come si fa? tu non hai i super poteri nel mio repo?

**Comment by aborruso** [comment]
@gbvitrano nei repo personali, sono il creatore può cambiare i settings. Ho messo il link alla guida nel mio messaggio.

Grazie (senza alcuna fretta)

**Comment by aborruso** [comment]
al momento non lo facciamo
