### ISSUE TITLE
traduzione in italiano

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#11]
questa parte va messa da qualche parte

https://github.com/pigreco/HfcQGIS#traduzione-in-italiano

![image](https://user-images.githubusercontent.com/7631137/42639988-9531b482-85f1-11e8-89ab-11bcb718a29e.png)

**Comment by gbvitrano** [comment]
la inserisco nella ho a fonfo pagina?

**Comment by pigreco** [comment]
@gbvitrano 
forse l'immagine risulta illeggibile, meglio trasformarla in testo, ci penso io e incollo qui il risultato

**Comment by pigreco** [comment]
@gbvitrano comunque vedi tu quale soluzione adottare testo o immagine:

testo:
La descrizione delle funzioni in italiano è stata realizzata dal gruppo di traduttori diretti da [Stefano Campus](https://twitter.com/skampus1967?lang=it)

---
Marco Grisolia, Roberto Angeletti, Michele Beneventi, Marco Braida, Stefano Campus, Luca Casagrande, Paolo Cavallini, Giuliano Curti, Luca Delucchi, Alessandro Fanna, Michele Ferretti, Matteo Ghetta, Anne Gishla, Maurizio Napolitano, Flavio Rigolon

immagine:
![image](https://user-images.githubusercontent.com/7631137/42680079-3e76d0c6-8684-11e8-8ba7-edc49ae6824a.png)

**Comment by gbvitrano** [comment]
fatto
ho messo il testo cosi i nomi del gruppo vengono indicizzati :-)
