### ISSUE TITLE
Modifica in blocco su tutti i file md contenuti nella cartella gr_funzioni

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#12]
In tutti i file .md contenuti nella cartella gr_funzioni (e nelle sue sottocartelle) rimuovere il carattere ` presente  nella prima riga

**Comment by gbvitrano** [comment]
Si giusto da # `aggregate`  
ad  # aggregate

se è possibile controllare anche che nella prima riga non ci sia un titolo con due ##

**Comment by aborruso** [comment]
ok quindi anche modificare nella prima riga `##` in `#`

**Comment by pigreco** [comment]
@aborruso si occorre togliere l'effetto dovuto a Alt +96 cioè `
![image](https://user-images.githubusercontent.com/7631137/42679654-03565a3a-8683-11e8-969a-2624503fbf6a.png)

**Comment by pigreco** [comment]
@aborruso 
> ok quindi anche modificare nella prima riga ## in #

si, dove è presente

**Comment by aborruso** [comment]
@pigreco c'è un altro pezzo su cui vorrei conferma: solo in tutti i file .md contenuti nella cartella gr_funzioni (e nelle sue sottocartelle)?

Grazie

**Comment by pigreco** [comment]
@aborruso 

> @pigreco c'è un altro pezzo su cui vorrei conferma: solo in tutti i file .md contenuti nella cartella gr_funzioni (e nelle sue sottocartelle)?

si, solo nei file .md

**Comment by pigreco** [comment]
@aborruso 
occorre agire solo nei file .md e solo all'interno della cartella **gr_funzioni** ed eventuali sottocartelle

**Comment by pigreco** [comment]
@aborruso per me puoi metterti in azione, leggi prima #13

**Comment by pigreco** [comment]
@aborruso 
potresti documentare come hai fatto?
con calma grazie

**Comment by aborruso** [comment]
Ho usato l'utility [fd](https://github.com/sharkdp/fd) (che cerca file su disco). Sono entrato nella cartella gr_funzioni e ho dato

    fd -e md -x sed -ir '1!b;s/`//g;s/Funzione//g;s/ +/ /g;s/##/#/g' {}

- cerco per estensione md;
- e poi eseguo con `-x` il comando sed, per fare un trova e sostituisci solo nella prima riga

**Comment by gbvitrano** [comment]
ottimo :-) sei magico
