### ISSUE TITLE
file.md da sostituire all'interno delle cartelle Variabili e Reference

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#13]
@aborruso @gbvitrano 
Purtroppo non ho ancora capito come gestire un repository forkato dal mio e per evitare danni allego qui un file zippato [variabili_reference.zip](https://github.com/gbvitrano/HfcQGIS/files/2192004/variabili_reference.zip) che contiene due cartelle **variabili** e **reference**, all'interno ci sono i file .md con le correzioni e aggiunte: (corretto prima riga e aggiunta immagine per paypal).

i file .md devono essere sostituiti con quelli presenti nelle relative cartelle di questo repo.

**Comment by pigreco** [comment]
@gbvitrano dopo che @aborruso ha terminato le modifiche in blocco #12 potresti scaricarti la cartella nel tuo git e fare le dovute sostiruzioni dei file .md

L'azione di andy non comporta problemi nei file .md da sostituire.

**Comment by gbvitrano** [comment]
fatto
 ho anche messo l'immagine al centro e cambiato l'indirizzo delle immagini
