### ISSUE TITLE
Proposta: rimuovere in home "Benvenuti" e immagini in alto

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#14]
@pigreco @gbvitrano chi arriva nel sito dovrebbe subito leggere di che si tratta. Mentre per ora non è così.
Specie da mobile.

Vi propongo di modificare la home da:

![image](https://user-images.githubusercontent.com/30607/42686006-e2400802-8694-11e8-8f4f-647425b4b524.png)

a

![image](https://user-images.githubusercontent.com/30607/42686015-e95b1b90-8694-11e8-8ad3-edbac0a818ca.png)

**Comment by pigreco** [comment]
Interessante osservazione.
Per me va bene la modifica.

**Comment by gbvitrano** [comment]
Si giusto

**Comment by gbvitrano** [comment]
![schermata 2018-07-13 alle 13 56 13](https://user-images.githubusercontent.com/20488693/42690530-cee67538-86a4-11e8-961f-a18f2d4daa3c.png)
![schermata 2018-07-13 alle 13 56 44](https://user-images.githubusercontent.com/20488693/42690531-d1dc6a0e-86a4-11e8-9328-fd04e31ba5c3.png)
![schermata 2018-07-13 alle 13 57 00](https://user-images.githubusercontent.com/20488693/42690534-d4926ee2-86a4-11e8-92f5-1a9e56087818.png)

fatto :-)

**Comment by gbvitrano** [comment]
Volendo il Titolo potrebbe diventare  da 
HfcQGIS: Help funzioni calcolatore di campi di QGIS

a: Help funzioni calcolatore di campi di QGIS

c'è il loghetto Hfc

**Comment by gbvitrano** [comment]
![schermata 2018-07-13 alle 14 07 03](https://user-images.githubusercontent.com/20488693/42691037-ccc8b458-86a6-11e8-8e2a-bcb869c99a26.png)

fatto
