### ISSUE TITLE
GDPR, cookie, ecc.

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#16]
Ciao,
non sono un esperto, ma credo che non possiamo tenere accese le statistiche senza predisporre una serie di avvisi.

Non ho la soluzione, non è tema mio, mi spiace :(

**Comment by gbvitrano** [comment]
https://docs.readthedocs.io/en/latest/privacy-policy.html?highlight=Google

**Comment by gbvitrano** [comment]
da capire come si comportatano glialtri siti in RTD

**Comment by gbvitrano** [comment]
Oltre a Google Analytic che cocontrolliamo noi come la mettiamo con il banner pubblicitari di RTD?
Guardando il codice del file html compliato non ho visto lo scrpt/codice  di  Google Analytic

**Comment by gbvitrano** [comment]
chi è il titolare del trattamento dati?

**Comment by gbvitrano** [comment]
Il testo della privacy che ho utilizzato su http://palermohub.opendatasicilia.it/info.html
dobrebbe andar bene, tranne per la voce sulla pubblicità, si HfcQGIS c'è

**Comment by aborruso** [comment]
@gbvitrano io non ne ho idea in modo esatto :(

**Comment by gbvitrano** [comment]
http://hfcqgis.opendatasicilia.it/it/latest/privacy.html

**Comment by gbvitrano** [comment]
Sono presenti annunci di pubblicità etica di Read the Docs che rispetta la privacy degli utenti. 
La pubblicità etica è la fonte princiaple del progetto Read the Docs.
