### ISSUE TITLE
Foglio di stile: per ora è rotto

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#17]
Che ne pensate di questa soluzione che è pronta e dovrebbe funzionare?

Lo stile bianco nella sidebar è problematico.

![image](https://user-images.githubusercontent.com/30607/42698660-dc5d1202-86be-11e8-9a6b-2514dc8d0736.png)

**Comment by pigreco** [comment]
Mi piace ma occorrerebbe provarla.

**Comment by gbvitrano** [comment]
adesso funziona, ma non sono molto sodisfatto.
Nella 2.0 lo cambio :-) 
lascio aperto cosi mi ricordo
