### ISSUE TITLE
Preparare post di lancio

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#18]
Scrivere un blog post per il lancio, da pubblicare su ODS, pigreco, ecc.

**Comment by pigreco** [comment]
Ottima idea!

**Comment by pigreco** [comment]
Ora che ci penso, avevo già scritto un post
https://pigrecoinfinito.wordpress.com/2018/05/21/hfcqgis/

lo recuperiamo?

**Comment by gbvitrano** [comment]
@pigreco nel post e video (se lo prepari) devi dare molta importanza alla **breadcrumbs** ed al cerca
La  breadcrumbs ti permette velocemente di navigare il Gruppo delle funzioni e le relative funzioni. 
![screenshot_2018-07-13 hfcqgis - help funzioni calcolatore di campi di qgis](https://user-images.githubusercontent.com/20488693/42711814-a612c194-86e9-11e8-8001-3bce79190044.png)

In questo esempio stiamo consultanto la funzione count_missing del gruppo  Aggregates

Cliccando su  **Aggregates** passi velocemente all'index del **gruppo  Aggregates**
se invece clicchi su **Elenco funzioni QGIS** passi rapidamente all'indice dei gruppi di funzione.
Il manuale è **facile** da usare e navigabile da mobile e fisso con qualsiasi dispositivo

Magari questo la metto anche manuale :-)
Risoluzione video: Per Pc con scheda video SVGA. Monitor a risoluzione minima di 1024x768 pixel con almeno 65.536 colori.
Per mobile, risoluzione minima di 360 x 640 px (modello di riferimento Sansung Galaxy Note3 o Sansung Galaxy S5).
Browser: Il sito è ottimizzato per Microsoft Internet Explorer Versione 11.0 e successive, Microsoft Edge versione 25.1e immediatamente successive, Mozilla Firefox versione 50.0 e successive o Chrome versione 40.0 o successiva, Opera versione 48.0 o successiva Safari versione 9.0 o successiva

**Comment by gbvitrano** [comment]
@pigreco sicuramente lo puoi citare, cmq nel vecchio post hai spiegato l'enorme lavoro che hai fatto per costruirlo, in questo caso devi spiegare come l'hai reso user friendly

**Comment by pigreco** [comment]
@gbvitrano il blog post possiamo scriverlo a 6 mani, ognuno scrive la sua parte, che ne dite?

**Comment by gbvitrano** [comment]
@pigreco scrivere non è cosa mia :-) sono negato, posso darti idee e tu le traduci :-) :-) :-)

**Comment by pigreco** [comment]
Ieri vi ho condiviso questo [gdoc](https://docs.google.com/document/d/1j3jyYWPeNXxcPjwo8XTMVYOHPj0jGQ9XvGSjlZx7g4Y/edit)
sto scrivendo qualcosa, se avete idee proponete pure.

**Comment by aborruso** [comment]
Io preparo quello per Open Data Sicilia

**Comment by pigreco** [comment]
qui la mia bozza su Medium

https://medium.com/p/d570cdf12043/edit

stesso testo ed immagini anche su Wordpress
