### ISSUE TITLE
alcune correzioni da fare

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#20]
1. Gruppo Record e attributi → $map manca link;
2. Esempi uso delle funzioni:
  2.1 Come aggiungere campo virtuale → $length manca link;
  2.2 Etichettare punti EPSG 4326 → funzione floor manca link
3. Novità, alla fine prima del video manca link ad esempi.

**Comment by gbvitrano** [comment]
Record e attributi → $map manca link; manca il file map.md nella cartella
Gli altri errori sono stati corretti

**Comment by pigreco** [comment]
Ottimo lavoro,
la funzione $map non esiste in quel gruppo, quindi occorre eliminarla.

**Comment by pigreco** [comment]
@gbvitrano 
nel gruppo funzioni [maps](https://github.com/gbvitrano/HfcQGIS/blob/master/gr_funzioni/maps/index.rst), sotto lo screenshot manca la solita tabella con tutte le funzioni del gruppo

![image](https://user-images.githubusercontent.com/7631137/42735027-d427c6be-884d-11e8-8d7d-4cb753f29fb1.png)

**Comment by pigreco** [comment]
gruppo campi e valori, da correggere:
![image](https://user-images.githubusercontent.com/7631137/42735643-4bf2ebd8-8858-11e8-806f-7f96339d33df.png)

**Comment by pigreco** [comment]
Gruppo Layer della mappe: non funziona link in get_feature
![image](https://user-images.githubusercontent.com/7631137/42735665-b95b2622-8858-11e8-95c7-e836e9e62a9b.png)

**Comment by gbvitrano** [comment]
ok controllo tutto :-)

**Comment by pigreco** [comment]
@gbvitrano 
da correggere:
gruppo **Geometria** nella tabella, colonna QGIS, compaiono asterischi 
![image](https://user-images.githubusercontent.com/7631137/42799438-21470040-8998-11e8-9db6-c15f42ec9025.png)

poi,
in **Elenco funzioni QGIS** occorre modificare il nome del campo _nro funzioni_ in
_nro funzioni gruppo/funzioni documentate_

![image](https://user-images.githubusercontent.com/7631137/42799530-7d5590ae-8998-11e8-8d01-35a752379e8d.png)

**Comment by pigreco** [comment]
@gbvitrano ecco come risolvere il problema:

![image](https://user-images.githubusercontent.com/7631137/42800289-7c6ea998-899b-11e8-83dc-bcca36564039.png)

**Comment by gbvitrano** [comment]
modifiche fatte
