### ISSUE TITLE
Proposta: rimuovere download di pdf e epub

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#22]
Ciao,
non li controlliamo bene e l'output non è un granché. Per la prima release, li disabiliterei

**Comment by pigreco** [comment]
Per me va bene rimuoverli.

**Comment by gbvitrano** [comment]
anche per me va bene, si disattivano dal progetto RDT, giusto?

**Comment by pigreco** [comment]
nel progetto RTD
https://readthedocs.org/dashboard/hfcqgis/advanced/


![image](https://user-images.githubusercontent.com/7631137/42723291-8f88d068-875b-11e8-8d4d-1348057d2c0a.png)

**Comment by gbvitrano** [comment]
Disattivato.
