### ISSUE TITLE
Link Autore

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#28]
Il link a Salvatore Fiandaca nel paragrafo Autore della Home punta a Twitter?
prima puntava alla miniBio

**Comment by gbvitrano** [comment]
Anche nel readme del tuo github punta a Twitter
dammi il link a cui deve puntare

**Comment by pigreco** [comment]
@gbvitrano ormai sono cose diverse il mio repo dal quello tuo forkato.
il link a cui puntare dovrebbe essere questo:
https://github.com/gbvitrano/HfcQGIS/blob/master/autore.md

devo ancora completare la bio

**Comment by pigreco** [comment]
Visto che in rst ad uno stesso nome punta lo stesso link, propongo di sostituire, nel paragrafo **Questo manuale**, a Salvatore → Totò e lasciare _Salvatore Fiandaca_ nel paragrafo **Autore**

**Comment by pigreco** [comment]
Risolto, chiudo issue!!!
