### ISSUE TITLE
Disclaimer - Visual Style Guide QGIS

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#29]
Sarebbe opportuno aggiungere:

I colori utilizzati in questo RTD sono fedeli alla [Visual Style Guide](https://www.qgis.org/en/site/getinvolved/styleguide.html#primary-colors)

**Comment by gbvitrano** [comment]
Aggiunto

**Comment by pigreco** [comment]
@gbvitrano 
per favore modifiche da:
I colori utilizzati in questo RTD sono fedeli alla [Visual Style Guide](https://www.qgis.org/en/site/getinvolved/styleguide.html#primary-colors) 

in

I colori utilizzati in questo RTD sono fedeli alla [Visual Style Guide](https://www.qgis.org/en/site/getinvolved/styleguide.html#primary-colors) di **QGIS**

**Comment by gbvitrano** [comment]
modificato
