### ISSUE TITLE
Migliorare visualizzazione ombra raster

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#30]
Per un migliore effetto ombra aumento il margine di questi due raster:

![image](https://user-images.githubusercontent.com/7631137/42732149-d3f3fe10-881b-11e8-97d9-b81ad37a5338.png)

![image](https://user-images.githubusercontent.com/7631137/42732154-e68b38c2-881b-11e8-93d5-0cfc4fad0a84.png)

**Comment by gbvitrano** [comment]
ho risolto creando una nuova classe css

/* immagine no bordo/ no ombra */
.immagonobox {
	max-width: 100%!important;
    height: auto!important;
	box-shadow: none !important;
	border: none !important;
	border-radius:  none !important;
	moz-border-radius: none !important;
	-webkit-border-radius: none !important;
	background-color: transparent !important;
	}

**Comment by pigreco** [comment]
@gbvitrano ottimo lavoro, chiudo issue!
