### ISSUE TITLE
pulizia immagini non usate

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#32]
nella cartella [/img](https://github.com/gbvitrano/HfcQGIS/tree/master/img), che contiene molte immagini, occorrerebbe fare una pulizia di immagini non utilizzate, magari un attimo prima del lancio. :-)

**Comment by gbvitrano** [comment]
ho creato una cartella **in_progress** all'interno della cartella **img** dove ho spostato tutte le immagini elaborate da me e servite come test, per tutte le altre non so quali sono collegate hai file e quali no.
