### ISSUE TITLE
inserire un iframe

### ISSUE THREAD

**Issue by gbvitrano** [gbvitrano/HfcQGIS#33]
Velevo inserire lo snippet nella home, ma non ci riesco.
ho copiato il codice di Totò in nuovo file snippet.md

Grarda in giro ho visto diversi modi.
**ho provato:**
|snippet|

.. |snippet| raw:: html
<iframe width="100%" height="100px" frameBorder="0" src="snippet.html"></iframe>

**Poi**
|snippet|

.. |snippet| raw:: html 
     :file: snippet.html

**ancora**
.. include:: snippet.md
in quest'ultimo caso viene carico il testo

**Comment by pigreco** [comment]
@gbvitrano ma ti riferisci a questa immagine?

<a href="https://stackexchange.com/users/8482031/pigreco"><img src="https://stackexchange.com/users/flair/8482031.png" width="208" height="58" alt="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" title="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" /></a>

il codice è questo:
```
<a href="https://stackexchange.com/users/8482031/pigreco"><img src="https://stackexchange.com/users/flair/8482031.png" width="208" height="58" alt="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" title="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" /></a>
```

**Comment by pigreco** [comment]
<a href="https://stackexchange.com/users/8482031/pigreco"><img src="https://stackexchange.com/users/flair/8482031.png" width="208" height="58" alt="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" title="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" /></a>
```

**Comment by gbvitrano** [comment]
la pagina è in rst e il codice html non va

**Comment by aborruso** [comment]
proposta per @gbvitrano e @pigreco: in home io metterei soltanto "Autore HfcQGIS", seguito da "Salvatore Fiandaca (aka pigreco)".

E poi sul nome link a http://hfcqgis.opendatasicilia.it/it/latest/autore.html

`autore` è un file markdown e si può mettere anche HTML.

**Comment by pigreco** [comment]
ok, faremo come suggerito da @aborruso - chiudo

**Comment by gbvitrano** [comment]
finalmente ho capito come inserire codice html in rst 

```
.. raw:: html

    <embed>
        <a href="https://stackexchange.com/users/8482031/pigreco"><img src="https://stackexchange.com/users/flair/8482031.png" width="208" height="58" alt="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" title="profile for pigreco on Stack Exchange, a network of free, community-driven Q&amp;A sites" /></a>
    </embed>
```
