### ISSUE TITLE
Il box con le pubblicità non è visibile

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#35]
Usare uno sfondo scuro

![image](https://user-images.githubusercontent.com/30607/42744895-075b04f6-88d0-11e8-9f1f-5b09dbe4b2b3.png)

**Comment by aborruso** [comment]
chiuso con https://github.com/gbvitrano/HfcQGIS/commit/b1e514b646db06967067e689693f6f55744be3a1

**Comment by gbvitrano** [comment]
@aborruso la soluzione va bene quando la pubblicità è sulla sx
![screenshot_2018-07-16 hfcqgis - help funzioni calcolatore di campi di qgis](https://user-images.githubusercontent.com/20488693/42747462-c0f999de-88dc-11e8-8ce6-f41bc1e49402.png)

ma quando passa sulla dx il problema si ripresenta :-( 

![screenshot_2018-07-16 hfcqgis - help funzioni calcolatore di campi di qgis 1](https://user-images.githubusercontent.com/20488693/42747482-d7eb9f0c-88dc-11e8-94f5-f9d0262c270e.png)

ho rimodifcato il codice del blocco pubblicità

```
div.ethical-text {color: #404040 !important;}
.ethical-sidebar .ethical-callout, .ethical-footer .ethical-callout {color: #404040!important;}
.ethical-rtd .ethical-sidebar a, .ethical-rtd .ethical-sidebar a:visited, .ethical-rtd .ethical-sidebar a:hover, .ethical-rtd .ethical-sidebar a:active {color: #404040!important; }
```
![screenshot_2018-07-16 hfcqgis - help funzioni calcolatore di campi di qgis 2](https://user-images.githubusercontent.com/20488693/42748055-fe212550-88de-11e8-9abb-182c81c7fb17.png)

![screenshot_2018-07-16 hfcqgis - help funzioni calcolatore di campi di qgis 3](https://user-images.githubusercontent.com/20488693/42748062-03a794d2-88df-11e8-80ef-1c01b8207f38.png)

**Comment by aborruso** [comment]
Ok, non mi ricordavo ci fosse pure in basso, grazie

**Comment by gbvitrano** [comment]
https://github.com/gbvitrano/HfcQGIS/commit/7cabbf6ee7b2ee80419b6350027e4e2048645a85#diff-81160707f0e75e1ec5a632589afda0bb

**Comment by gbvitrano** [comment]
7cabbf6

finalmete ho capito come fai il link solo alla modifica :-)
