### ISSUE TITLE
inserire hashtag automatici nella condivisione social

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#36]
![image](https://user-images.githubusercontent.com/7631137/42752118-3c5a5f86-88ed-11e8-9c11-3beb7b6a381d.png)

è importante usare i giusti hashtag,
è possibile farlo?

**Comment by gbvitrano** [comment]
fino ad ora ho trovato solo questo sito https://shareaholic.com/ ma #HfcQGIS si può mettere solo nella condivisione di twitter 
![screenshot 28](https://user-images.githubusercontent.com/20488693/42758810-07c9f4bc-8905-11e8-8d1a-f65e50d0b7f2.jpg)

e non è possibile condividere tramite telegram
