### ISSUE TITLE
Modificare URL assoluti in relativi

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#39]
Modificare URL come [questo](https://github.com/gbvitrano/HfcQGIS/blob/master/_templates/layout.html#L20) in relativo

```<script type="text/javascript" src=" http://hfcqgis.opendatasicilia.it/it/latest/_static/jquery.backTop.min.js"></script>```

**Comment by gbvitrano** [comment]
quindi diveterebbe cosi 
`<script type="text/javascript" src="../_static/jquery.backTop.min.js"></script>`

**Comment by aborruso** [comment]
@gbvitrano faccio una prova io

**Comment by aborruso** [comment]
@gbvitrano ho modificato il file layout.html usando la funzione pathto

Come qui https://github.com/gbvitrano/HfcQGIS/blob/master/_templates/layout.html#L21

Ho testato con http://hfcqgis.readthedocs.io/it/latest/ e tutto sembra ok.

Puoi verificare e nel caso chiudi tu la issue?

**Comment by gbvitrano** [comment]
Buono a sapersi, grazie grazie :-)
