### ISSUE TITLE
CSS: rendere leggibile blocco in sidebar

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#4]
Al momento il blocco RTD non è leggibile

![image](https://user-images.githubusercontent.com/30607/42563099-ad608208-84fd-11e8-9f60-2a15490b39f7.png)

**Comment by gbvitrano** [comment]
fino ad ora non c'è verso, provo a a mettere il testo del colore originale e faccio lo scuro lo sfondo del quadrato

**Comment by gbvitrano** [comment]
Risoloto

https://screenshots.firefox.com/xH0tp9COvk2hDIDz/hfcqgis.readthedocs.io
