### ISSUE TITLE
Creare e pubblicare elenco delle funzioni non ancora documentate

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/HfcQGIS#47]
Creato l'elenco, creerei una pagina da pubblicare su http://hfcqgis.opendatasicilia.it, e dargli evidenza nella pagina [Contribuire a HfcQGIS](http://hfcqgis.opendatasicilia.it/it/latest/contributing.html).

Qualcosa come "Vuoi documentare una funzione? Ecco quelle ancora non pronte"

**Comment by pigreco** [comment]
allego elenco funzioni da documentare
mio [repo](https://github.com/pigreco/HfcQGIS/tree/master/milestone2_hfcqgis%2347)

**Comment by aborruso** [comment]
@pigreco è un elenco che si può generare automaticamente? Se sì come?

**Comment by pigreco** [comment]
@aborruso nel mio repo ho la cartella [funzioni](https://github.com/pigreco/HfcQGIS/tree/master/gr_funzioni/variabili/funzioni) -per ogni gruppo funzioni- che contiene tutte e solo le funzioni del gruppo; nel repo di gb questa [cartella](https://github.com/gbvitrano/HfcQGIS/tree/master/gr_funzioni/variabili) non esiste e all'interno del gruppo trovi anche altri file (readme.md, index.rst)

per generarlo automaticamente, partendo dal repo di gb, occorrerebbe puntare nella [cartella](https://github.com/gbvitrano/HfcQGIS/tree/master/gr_funzioni/variabili) e selezionare tutti i file *.md (tranne il readme) per il gruppo **Variabili** e poi nella cartella del gruppo **Reference**

**Comment by aborruso** [comment]
@pigreco non mi sono spiegato. Che il repo sia il tuo o quello di gb, come distinguo quelle non ancora documentate? C'è dentro qualche stringa di testo che hanno soltanto le non documentate?

Grazie

**Comment by pigreco** [comment]
@aborruso mi sono spiegato male. Ad oggi solo due gruppi (Reference e Variabili) contengono funzioni non documentate. Tutte le funzioni di questi gruppi contengono un discriminate che è questo codice:


`<a href="https://www.paypal.me/pigrecoinfinito" target="_blank"><img width="700" src="https://github.com/pigreco/HfcQGIS/blob/master/img/sviluppo_variabili_01.png" Title="La documentazione di questa funzione non è stata ancora sviluppata. Se vuoi sostenerla fai una donazione con PayPal, scrivendo ..." alt="Donazione HfcQgis" /></a>`

che punta a due immagini:
sviluppo_variabili_01.png - caso gruppo variabili
sviluppo_reference_01.png - caso gruppo reference

**Comment by aborruso** [comment]
Con questo comando 

    grep -l -r -i --include \*.md  'paypal.me' ./gr_funzioni >./gr_funzioni/da_documentare.txt

si genera la lista https://github.com/gbvitrano/HfcQGIS/blob/master/gr_funzioni/da_documentare.txt

@pigreco e @gbvitrano se mi dite come deve essere fatta la pagina markdown con l'elenco di queste funzioni non documentate, creo lo script che la genera in modo programmatico

**Comment by pigreco** [comment]
@aborruso ho appena aggiunto altre tre funzioni nel gruppo **Reference** quindi occorre rifare il file `da_documentare.txt` (dovrebbero risultare 21+65)

Secondo me la pagina potrebbe essere cosi: 

## Vuoi documentare una funzione? Ecco quelle ancora non pronte

### Gruppo **Reference**

Funzione  | Descrizione
:----------:|:-----------
dbvalue | Recupera il primo valore targetField da targetLayer quando keyField è uguale a conditionValue
dbvaluebyid | Recupera il valore targetField da targetLayer usando l'ID della caratteristica interna
...|...

### Gruppo **Variabili**

Funzione  | Descrizione|applicazione
----------:|:-----------|-----------:
atlas_feature|Ritorna la geometria attuale dell'atlante  (come oggetto geometria)|proprietà del layer, geometry generator
atlas_featureid|Ritorna ID della geometria attuale dell'atlante|proprietà del layer, geometry generator
...|...|...

e alla fine delle tabella:

<a href="https://www.paypal.me/pigrecoinfinito" target="_blank"><img width="400"  class="immagonobox" src="https://raw.githubusercontent.com/pigreco/HfcQGIS/master/img/sviluppo_variabili_01.png" Title="La documentazione di questa funzione non è stata ancora sviluppata. Se vuoi sostenerla fai una donazione con PayPal, scrivendo ..." alt="Donazione HfcQgis" style="margin: 0 auto; display: block;" /></a>

**Comment by aborruso** [comment]
@pigreco @gbvitrano ho creato uno [script](https://github.com/gbvitrano/HfcQGIS/blob/master/script/toDoc.sh) che crea [questa pagina](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/da_documentare.html) in automatico.

Che ve ne pare? A voi decidere dove dargli visibilità

**Comment by pigreco** [comment]
@aborruso grazie ottimo script
per me va benissimo
@gbvitrano è il grafico, per me puo' decidere lui dove metterlo. 👍

**Comment by pigreco** [comment]
Come usare/lanciare lo script: (da win 10 occorre aver installato la [bash](https://docs.microsoft.com/en-us/windows/wsl/install-win10) di ubuntu 16.04)
1. recarsi nella cartella dello script e scrivere **bash** nel campo dei percorsi;

![image](https://user-images.githubusercontent.com/7631137/43409636-c72967dc-9424-11e8-9277-e11b066975a6.png)


2. digitare: ./toDocs.sh

![image](https://user-images.githubusercontent.com/7631137/43407396-f40dc06e-941e-11e8-9c54-caf23f495740.png)

3. in pochissimi secondi avremo il risultato atteso.

**Comment by aborruso** [comment]
@pigreco io questa issue la chiuderei. Se sei d'accordo, fallo per favore
