### ISSUE TITLE
creare pagina in RTD - si parla di questa guida...

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#49]
creare una pagina in cui raccogliere tutti gli articoli e video dedicati alla guida

**Comment by gbvitrano** [comment]
La pagina va attivata dopo il lancio ufficiale, se il nuova versione html piace, ne parleranno tutti nel settore QGIS,  gruppi facebook, blog vari, e riviste di settore spero :-) 
Basta il primo gruppo facebook dove se ne discute per attivare la pagina :-)

**Comment by pigreco** [comment]
ho abbozzato qui alcuni link

https://github.com/pigreco/HfcQGIS/blob/master/parlano_di_noi.md

**Comment by aborruso** [comment]
È un'ottima idea

**Comment by pigreco** [comment]
Buongiorno, @gbvitrano e @aborruso 
se mi date qualche qualche indicazione provo ad aggiungere la pagina al menu laterale :-)

grazie
