### ISSUE TITLE
piccoli errori da correggere

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#56]
[qui ](https://github.com/gbvitrano/HfcQGIS/blob/master/gr_funzioni/matematica/floor.md#osservazioni)il link non funzione nonostante sembra corretto
![image](https://user-images.githubusercontent.com/7631137/43504058-2c13a5a2-9562-11e8-9f64-0792415fad9b.png)

**Comment by gbvitrano** [comment]
Corretto, 
``` ../../esempi/conversione.html```

l'indirizzo era sbagliato
