### ISSUE TITLE
pagina statistiche

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#70]
aggiungiamo una pagina statistiche di HfcQGIS??

ecco un esempio [0]
consigli, miglioramenti??

[0] https://github.com/pigreco/HfcQGIS/blob/master/statistiche.md

**Comment by gbvitrano** [comment]
Come base va bene.
Possiamo realizzare una dashboard di Analytics personalizzata e  se riesco a farla caricare dinamicamente è meglio :-)
