### ISSUE TITLE
Tabella sinottica con valori aggregati per ogni gruppo

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#71]
Con questo comando, lanciato nella cartella **HfcQGIS** (mio [repo](https://github.com/pigreco/HfcQGIS))

`grep -l -r -i --include \*.md  '## Esempi' ./gr_funzioni >./gr_funzioni/tabella_sinottica_aggr.txt`

ottengo questo file: https://github.com/pigreco/HfcQGIS/blob/master/gr_funzioni/tabella_sinottica_aggr.txt

come ottenere questa tabella sinottica in un unico ~~comando~~ script usando [visidata](https://medium.com/tantotanto/visidata-il-coltellino-svizzero-per-i-dati-che-probabilmente-non-conosci-2209ffd4fa39)??
https://github.com/pigreco/HfcQGIS/blob/master/gr_funzioni/testone2_c_freq.md

gruppo|count|percent|histogram
--------|-----|-------|--------
geometria|101|25.00|**************************************************
variabili|65|16.09|********************************
arrays|32|7.92|***************
matematica|28|6.93|*************
aggregates|22|5.45|**********
stringhe_di_testo|22|5.45|**********
operatori|21|5.20|**********
reference|21|5.20|**********
colore|17|4.21|********
data_ora|16|3.96|*******
maps|14|3.47|******
conversioni|9|2.23|****
record_e_attributi|9|2.23|****
condizioni|6|1.49|**
generale|6|1.49|**
custom|5|1.24|**
corrispondenza_fuzzy|4|0.99|*
array|2|0.50|
layer_della_mappa|2|0.50|
rasters|2|0.50|

**Comment by aborruso** [comment]
@pigreco in un unico comando cosa intendi? Si fa a step.

Vuoi registrare una sorta di macro, da lanciare quando serve?

**Comment by pigreco** [comment]
Ciao Andrea,

> Vuoi registrare una sorta di macro, da lanciare quando serve?

sì.

Ho sbagliato a scrivere: intendevo in un unico **script** usando anche visidata.

Cioè, dovrei riuscire a passare il file `tabella_sinottica_aggr.txt` a visidata, ma occorre prima modificarlo.

Il file `tabella_sinottica_aggr.txt` è cosi strutturato:

![image](https://user-images.githubusercontent.com/7631137/53694503-16f1e200-3db0-11e9-9e3d-2fe1dbee5052.png)

ma per passarlo a visidata occorre modificarlo per ottenere:

![image](https://user-images.githubusercontent.com/7631137/53694537-9c759200-3db0-11e9-9663-296cd7f0dcd2.png)

**Comment by aborruso** [comment]
Ciao totò,
per questo tipo di operazioni io uso Miller (http://johnkerl.org/miller/doc). 
Qui trovi gli eseguibili sia per Linux (mlr.linux.x86_64) che per Win: https://github.com/johnkerl/miller/releases

Una volta scaricato (dandogli il permesso di esecuzione e rinominandolo nel caso) il comando è questo

```bash
# apri il file separato da "/" e convertilo in markdown (--n2m), 
# raggruppandolo per valori univoci del terzo campo
mlr --n2m --ifs "/" uniq -g 3 -c \
# ordinalo per conteggio valori
then sort -nr count \
# aggiungi un campo etichetta in cui inserire i valori di conteggio e il campo con le percentuali
then put '$etichetta=$count;$perc=($count * 100 /NR)' \
# crea il grafico a barre basato sul campo count
then bar -b " " -x " " -f count \
# dai a 3 campi di output come nome i valori nome,bar,valore,percentuale
then label nome,bar,valore,percentuale \
# riordina i campi come nome,valore,percentuale,bar
then reorder -f nome,valore,percentuale,bar input.txt
```

In output avrai 

```
| nome | valore | percentuale | bar |
| --- | --- | --- | --- |
| geometria | 101 | 25 | ***************************************  |
| variabili | 65 | 16.089109 | **************************               |
| arrays | 32 | 7.920792 | ************                             |
| matematica | 28 | 6.930693 | ***********                              |
| aggregates | 22 | 5.445545 | ********                                 |
| stringhe_di_testo | 22 | 5.445545 | ********                                 |
| operatori | 21 | 5.198020 | ********                                 |
| reference | 21 | 5.198020 | ********                                 |
| colore | 17 | 4.207921 | ******                                   |
| data_ora | 16 | 3.960396 | ******                                   |
| maps | 14 | 3.465347 | *****                                    |
| conversioni | 9 | 2.227723 | ***                                      |
| record_e_attributi | 9 | 2.227723 | ***                                      |
| condizioni | 6 | 1.485149 | **                                       |
| generale | 6 | 1.485149 | **                                       |
| custom | 5 | 1.237624 | **                                       |
| corrispondenza_fuzzy | 4 | 0.990099 | *                                        |
| array | 2 | 0.495050 |                                          |
| layer_della_mappa | 2 | 0.495050 |                                          |
| rasters | 2 | 0.495050 |                                          |
```

Ovvero

| nome | valore | percentuale | bar |
| --- | --- | --- | --- |
| geometria | 101 | 25 | ***************************************  |
| variabili | 65 | 16.089109 | **************************               |
| arrays | 32 | 7.920792 | ************                             |
| matematica | 28 | 6.930693 | ***********                              |
| aggregates | 22 | 5.445545 | ********                                 |
| stringhe_di_testo | 22 | 5.445545 | ********                                 |
| operatori | 21 | 5.198020 | ********                                 |
| reference | 21 | 5.198020 | ********                                 |
| colore | 17 | 4.207921 | ******                                   |
| data_ora | 16 | 3.960396 | ******                                   |
| maps | 14 | 3.465347 | *****                                    |
| conversioni | 9 | 2.227723 | ***                                      |
| record_e_attributi | 9 | 2.227723 | ***                                      |
| condizioni | 6 | 1.485149 | **                                       |
| generale | 6 | 1.485149 | **                                       |
| custom | 5 | 1.237624 | **                                       |
| corrispondenza_fuzzy | 4 | 0.990099 | *                                        |
| array | 2 | 0.495050 |                                          |
| layer_della_mappa | 2 | 0.495050 |                                          |
| rasters | 2 | 0.495050 |                                          |

Lo script è da lanciare senza commenti

```bash
mlr --n2m --ifs "/" uniq -g 3 -c \
then sort -nr count \
then put '$etichetta=$count;$perc=($count * 100 /NR)' \
then bar -b " " -x " " -f count \
then label nome,bar,valore,percentuale \
then reorder -f nome,valore,percentuale,bar input.txt >./output.md
```

**Comment by pigreco** [comment]
Caro Andrea, funziona tutto perfettamente, grazie.

Aggiungo solo per me, per non scordarlo, come effettuare l'installazione di miller:

1. scaricare il file **mlr.linux.x86_64** in una cartella es: `download`
2. all'interno della cartella `download` digitare _**Bash**_ per entrare nel terminale;
3. `chmod +x mlr.linux.x86_64` per i permessi;
4. rinominare il file: `mv mlr.linux.x86_64 mlr`;
5. `sudo mv ./mlr /usr/bin` per spostarlo nella cartella `usr/bin` e quindi raggiungibile sempre

**Comment by pigreco** [comment]
Creato unico script, da lanciare dalla cartella **HfcQGIS**:

```bash
#!/bin/bash
set -x

# file bash da lanciare dalla cartella HfcQGIS
# crea file con elenco di tutte le funzioni
grep -l -r -i --include \*.md '## Esempi' ./gr_funzioni >./gr_funzioni/elenco_funzioni.txt

# crea quadro sinottico aggregato
mlr --n2m --ifs "/" uniq -g 3 -c \
then sort -nr count \
then put '$etichetta=$count;$perc=($count * 100 /NR)' \
then bar -b " " -x " " -f count \
then label nome,bar,valore,percentuale \
then reorder -f nome,valore,percentuale,bar ./gr_funzioni/elenco_funzioni.txt >./gr_funzioni/quadro_sinottico.md
```

Testato, funzione bene!
