### ISSUE TITLE
solo per i predicati geometrici presenti nel gruppo geometry

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#73]
Ho fatto questa piccola aggiunta da realizzare per circa 10 funzioni:

http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/crosses.html#osservazioni

cosa ne pensate??

**Comment by aborruso** [comment]
@pigreco che vuol dire? Io vedo che hai aggiunto le osservazione, che vuol dire che è da realizzare per 10 funzioni?

**Comment by pigreco** [comment]
@aborruso 

>che vuol dire che è da realizzare per 10 funzioni?

Nel gruppo `geometria` del field calc di QGIS sono presenti alcuni predicati geometrici utili per la selezione per posizione (`crosses`, `contains`, `intersects`, `within`, `disjoint`, `overlaps`, `touches`) solo per questi volevo aggiungere - nella sezione **osservazione** - un esempio pratico:

`crosses(geometry(get_feature( 'fiume_arno','nome','ARNO')), $geometry)`

dove:

* geometry a è `geometry(get_feature( 'fiume_arno','nome','ARNO'))`
* geometry b è `$geometry`

**Comment by aborruso** [comment]
ok, mi sembra una buona cosa

**Comment by pigreco** [comment]
Le modifiche sono queste:

1. [contains](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/contains.html#osservazioni)
2. [crosses](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/crosses.html#osservazioni)
3. [disjoint](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/disjoint.html#osservazioni)
4. [intersects](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/intersects.html#osservazioni)
5. [overlaps](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/overlaps.html#osservazioni)
6. [touches](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/touches.html#osservazioni)
7. [within](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/geometria/within.html#osservazioni)
