### ISSUE TITLE
cosa fare per gruppi funzioni non documentati

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#8]
Ci sono tre gruppi funzioni: Reference (21), TimeManager (5) e Variabili (64)  sono circa 90 funzioni che non li ho documentati per due motivi: 
![image](https://user-images.githubusercontent.com/7631137/42618581-bfb4b268-85b5-11e8-9891-293b3ccc0887.png)

1. mancanza di tempo e voglia di farlo;
2. per spronare la donazione;

scriviamo da qualche parte che la documentazione di questi gruppi verrà fatta solo dietro donazione?

**Comment by gbvitrano** [comment]
Si può scrivere all'inizio della pagina del prorpio index

**Comment by gbvitrano** [comment]
e si può mettere anche il collegamento con paypal

**Comment by pigreco** [comment]
Ok, per me va bene.

**Comment by pigreco** [comment]
@gbvitrano 
secondo me è inutile attivare il link, creerebbe solo confusione.

**Comment by gbvitrano** [comment]
questa si può chiudere? abbiamo risolta con l'immagine della donazione
