### ISSUE TITLE
manca testo e formattazione

### ISSUE THREAD

**Issue by pigreco** [gbvitrano/HfcQGIS#9]
qui qualcosa è saltato:
https://github.com/gbvitrano/HfcQGIS/blob/master/gr_funzioni/aggregates/index.rst#nota-bene

deve essere cosi:
https://github.com/pigreco/HfcQGIS/tree/master/gr_funzioni/aggregates#nota-bene

**Comment by gbvitrano** [comment]
Totò se rimetto https://github.com/pigreco/HfcQGIS/tree/master/gr_funzioni/aggregates#nota-bene

nel menù di sx tutte le funzioni andranno sotto Nota bene

**Comment by pigreco** [comment]
@gbvitrano 

> nel menù di sx tutte le funzioni andranno sotto Nota bene

se non esiste soluzione lasciala per come è.
